# Generated by Django 4.2 on 2023-04-14 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.CharField(max_length=255, verbose_name='Video Link'),
        ),
    ]
