# Generated by Django 4.2 on 2023-04-15 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default='djangodbmodelsfieldscharfield-tag', unique=True),
        ),
    ]
