# Generated by Django 4.2 on 2023-04-17 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_category_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.CharField(max_length=1024, verbose_name='Video Link'),
        ),
    ]
